[package]
cairo-version = "=2.8.4"
name = "shinigami_template"
version = "0.0.1"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.9" }
achievement = { git = "https://github.com/cartridge-gg/arcade", tag = "v1.0.9" }

[dev-dependencies]
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.9" }

[[target.starknet-contract]]
build-external-contracts = [
  "dojo::world::world_contract::world",
  "achievement::events::index::e_TrophyCreation",
  "achievement::events::index::e_TrophyProgression",
]

[tool.fmt]
sort-module-level-items = true
max-line-length = 120

[profile.sepolia]
[profile.slot]
[profile.release]
